### ISSUE TITLE
Issues while building

### ISSUE THREAD

**Issue by farleyknight** [gameclosure/native-android#24] opened 2015-04-05 16:18 UTC
I've been trying to get devkit to build the whack-that-mole sample game. It's not working and I'm digging deeper. During that dig, I found this repo and have been trying to run `make` but keep getting this error. Any ideas?:

```
android update project -p TeaLeaf --target android-19 --subprojects
Updated project.properties
Updated local.properties
Updated file TeaLeaf/proguard-project.txt
android update project -p GCTestApp --target android-19 --subprojects
Updated project.properties
Updated local.properties
Updated file GCTestApp/proguard-project.txt
ndk-build -C TeaLeaf -Bj8 RELEASE=0 JSPROF=1 GPROF=0 V8SYMBOLS=0
Android NDK: WARNING: APP_PLATFORM android-18 is larger than android:minSdkVersion 8 in ./AndroidManifest.xml
Android NDK: WARNING:jni/Android.mk:zip: LOCAL_LDLIBS is always ignored for static libraries
Android NDK: WARNING:jni/Android.mk:zip: LOCAL_LDLIBS is always ignored for static libraries
make[1]: Entering directory `/Users/farleyknight/Downloads/native-android/TeaLeaf'
make[1]: *** No rule to make target `jni/core/config.c', needed by `obj/local/armeabi/objs-debug/tealeaf/core/config.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/Users/farleyknight/Downloads/native-android/TeaLeaf'
make: *** [all] Error 2
```

**Comment by mgh** [comment] 2015-08-25 13:45
This is caused by https://github.com/gameclosure/native-android/issues/27 and is now fixed in the latest version.

This can also be fixed by running `make setup` first.

**Closed by mgh** 2015-08-25 13:45 UTC
